name: flutter_esc_pos_network
description: The library allows printing receipts using ESC/POS commands using thermal Wi-Fi/Ethernet printer.
version: 0.0.1
homepage: https://github.com/mjafartp/flutter_esc_pos_network

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_esc_pos_utils:
    git:
      url: git://github.com/fikrirazzaq/flutter_esc_pos_utils.git
      ref: c607c8cd51283ce3b0d04f960753a4aa0dd2ef9c

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
